### PR TITLE
Automatize time series generation by build_renewable_profiles

### PR DESCRIPTION
**Pull request by davide-f**
# Closes # (if applicable).

## Changes proposed in this Pull Request
Automatize the use of build_renewable_profiles to generate time series for renewable sources

## Checklist

- [ ] I tested my contribution locally and it seems to work fine.
- [ ] Code and workflow changes are sufficiently documented.
- [ ] Newly introduced dependencies are added to the main environment at [PyPSA-Earth repository](https://github.com/pypsa-meets-earth/pypsa-earth)
- [ ] Changes in configuration options are added in all of `config.default.yaml` and `config.tutorial.yaml`.
- [ ] Add a test config or line additions to `test/` (note tests are changing the config.tutorial.yaml)
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv` and line references are adjusted in `doc/configuration.rst` and `doc/tutorial.rst`.
- [ ] A note for the release notes `doc/release_notes.rst` is amended in the format of previous release notes, including reference to the requested PR.

### CODE REVIEW

**Comment by davide-f** [comment]
@DeniseGiub this PR now executes the workflow.
Little steps are needed before the actual merge as some chaining is not yet completely functional, especially in case of microgrids belonging to multiple countries but that's a different element.

**Comment by davide-f** [comment]
@DeniseGiub I confirm that this PR seems to have a working workflow.
Elements of attention: the renewable capacities can be calculated with different regions on/offshores according to the specific location of the microgrid and their space limitations.
Currently those are imported from pypsa-earth.

**Comment by DeniseGiub** [comment]
@davide-f I know that I still have to modify the rule "add_electricity" to add generation and storage to the grids. However, I honestly don't know how to calculate the specific renewable generation for each microgrid if not making changes to the script "build_renewable_profiles", so not importing generation profiles calculated in pypsa-earth. What do you think? Should I proceed with this?

**Comment by DeniseGiub** [comment]
@davide-f thanks! I am testing your changes locally (in a clean repo, not with the modifications of my PR) but I get this error:
atlite_error

**Pull request merged**
